defaultEntryPoints = ["http", "https"]
    [entryPoints]
      [entryPoints.http]
      address = ":80"
      [entryPoints.http.auth.forward]
      address = "http://auth"
      authResponseHeaders = ["X-Forwarded-User"]