branches:
  only:
  - master
  - testing-00001

matrix:
  include:
    - language: python
      python:
        - "3.7"
      install:
        - pip install -r requirements.txt
      script:
        - pytest tests/test_gitlab_controller.py

    - sudo: required
    - language: python
      python:
          - "3.7"
      services: 
        - docker
      env:
        global:
          - CLOUDSDK_CORE_DISABLE_PROMPTS=1
      before_install:
      - curl https://sdk.cloud.google.com | bash > /dev/null
      - source $HOME/google-cloud-sdk/path.bash.inc
      - gcloud components install kubectl
      script: 
        - kubectl version
        - pytest tests/test_kubernetes_controller.py