
apiVersion: v1
kind: Service
metadata:
  name: gitlab-charles
  annotations:
    external-dns.alpha.kubernetes.io/hostname: gitlab-charles.docker-desktop.securethebox.us
spec:
  selector:
    app: gitlab-charles
  ports:
  - name: http
    targetPort: 80
    port: 80
  - name: https
    targetPort: 443
    port: 443
  - name: ssh
    targetPort: 22
    port: 2222
              