
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: docker-desktop-charles-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
              